### ISSUE TITLE
Referral status not updated after card declined initially but order is later completed

### ISSUE THREAD

**Issue by tjackson1317** [AffiliateWP/affiliatewp-force-pending-referrals#13]
When a customer's card is first declined at checkout, but the order is later completed, the referral should automatically update from _Rejected_ to _Unpaid_. However, this automatic status update does not occur when the Force Pending Referrals add-on is active. Instead, the referrals remain in the _Rejected_ status even after the order has been successfully completed.

Below are testing examples with the same products purchased with Force Pending Referrals activated/deactivated. When it's deactivated, the referral's status is updated automatically as expected.

**EXAMPLE 1:**

![image](https://user-images.githubusercontent.com/55418074/114092323-be8f4780-9887-11eb-830f-467e8c6da1e3.png)

**_Referral #333_** 
![image](https://user-images.githubusercontent.com/55418074/114092804-4e34f600-9888-11eb-8d28-007ddb4ec5e3.png)

**_Referral #334_** 

![image](https://user-images.githubusercontent.com/55418074/114092908-6d338800-9888-11eb-836b-4a3a77157c23.png)

**EXAMPLE 2:**

![image](https://user-images.githubusercontent.com/55418074/114093105-b683d780-9888-11eb-992e-ba2e15ec72c1.png)

**_Referral #337_** 

![image](https://user-images.githubusercontent.com/55418074/114093263-e29f5880-9888-11eb-9964-862cfe066718.png)

**_Referral #338_** 

![image](https://user-images.githubusercontent.com/55418074/114093349-ff3b9080-9888-11eb-9f2a-cd3070090aa3.png)

**_Error shown in debug log:_** _Referral not marked as complete because of affwp_auto_complete_referral filter_

First reported on this ticket: 

https://secure.helpscout.net/conversation/1440065709/#thread-4183900379

The same customer has now responded a month later, so due to timing a new ticket was automatically opened regarding this issue:

https://secure.helpscout.net/conversation/1475335399/181809?folderId=205529

**Comment by tjackson1317** [comment]
The above customer inquired about a timeline today:

> Is there a rough idea how long that might take? We talking weeks, months, or more? 😅
> 
> Thank you!

**Comment by tjackson1317** [comment]
Same customer following up:

> We're doing this month manually now that Payday has come about and was hoping there would be an update to save me from checking every rejected manually, one at a time. I'm sure you can understand how long this task can take! Most of the rejected orders are incorrect and look like this: It doesn't say rejected here in order notes, however, then when I look at the affiliate status (and in the export) it shows as rejected (because the Card was declined)
> 
> ![image](https://user-images.githubusercontent.com/55418074/116935861-fc884d00-ac34-11eb-9f77-ca3292e3bd09.png)
> 
> ![image](https://user-images.githubusercontent.com/55418074/116935880-03af5b00-ac35-11eb-8560-20f2f95737c3.png)
> 
> So each order that has the rejected status I need to
> 
> - manually check the order number
> - look through the order and check if it has been paid
> - if it has been paid then change the referral from rejected to paid
> 
> It would be great if there is an estimate to when a fix for this bug could be applied - it's draining taking so long to do this one at a time. Thanks, Alex

**Comment by DrewAPicture** [comment]
@tjackson1317 Can you confirm what version of AffiliateWP this last customer is running? We recently pushed some changes that handle various new order and referral status transitions and I'm wondering if they're maybe running an older version of core that isn't covering this.

**Comment by tjackson1317** [comment]
@DrewAPicture I just tested this again with AffiliateWP 2.6.8 and latest WC (5.2.2). Looks like the conflict is still there unfortunately.

All 4 orders below are now _Completed_ in WC. 

When Force Pending Referrals is:
**Deactivated-**-The first 2 referrals updated to _Unpaid_ when the order was completed. 
**Activated**--The last 2 referrals still have the _Rejected_ status after order completed.

![image](https://user-images.githubusercontent.com/55418074/117068587-7bdf5480-acf9-11eb-9548-3efcc9e47f39.png)

**_Debug log:_**

2021-5-04 14:42:07 - Arguments being sent to DB:
array (
  \'amount\' => 1.8,
  \'reference\' => 1798,
  \'description\' => \'Happy Ninja\',
  \'campaign\' => \'\',
  \'affiliate_id\' => 9,
  \'visit_id\' => 93,
  \'order_total\' => \'18.00\',
  \'products\' => \'a:1:{i:0;a:4:{s:4:\"name\";s:11:\"Happy Ninja\";s:2:\"id\";i:37;s:5:\"price\";s:2:\"18\";s:15:\"referral_amount\";s:3:\"1.8\";}}\',
  \'custom\' => \'a:2:{s:12:\"affiliate_id\";i:9;s:18:\"is_coupon_referral\";b:0;}\',
  \'type\' => \'sale\',
  \'context\' => \'woocommerce\',
  \'customer\' => 
  array (
    \'user_id\' => 0,
    \'email\' => \'tjackstest38208@gmail.com\',
    \'first_name\' => \'Taylor\',
    \'last_name\' => \'Test\',
    \'ip\' => \'24.99.127.23\',
  ),
)2021-5-04 14:42:07 - Pending Referral #345 created successfully.
2021-5-04 14:42:07 - Referral #345 created successfully.
2021-5-04 14:42:10 - Referral retrieved successfully during reject_referral()
2021-5-04 14:42:10 - Referral #345 set to Rejected successfully
2021-5-04 14:42:39 - WooCommerce Referral #345 updated successfully.
2021-5-04 14:42:43 - Referral retrieved successfully during complete_referral()
2021-5-04 14:42:43 - Referral #345 set to Unpaid successfully
2021-5-04 20:48:50 - Arguments being sent to DB:
array (
  \'amount\' => 1.8,
  \'reference\' => 1799,
  \'description\' => \'Happy Ninja\',
  \'campaign\' => \'\',
  \'affiliate_id\' => 9,
  \'visit_id\' => 93,
  \'order_total\' => \'18.00\',
  \'products\' => \'a:1:{i:0;a:4:{s:4:\"name\";s:11:\"Happy Ninja\";s:2:\"id\";i:37;s:5:\"price\";s:2:\"18\";s:15:\"referral_amount\";s:3:\"1.8\";}}\',
  \'custom\' => \'a:2:{s:12:\"affiliate_id\";i:9;s:18:\"is_coupon_referral\";b:0;}\',
  \'type\' => \'sale\',
  \'context\' => \'woocommerce\',
  \'customer\' => 
  array (
    \'user_id\' => 0,
    \'email\' => \'tjackstest38208@gmail.com\',
    \'first_name\' => \'Taylor\',
    \'last_name\' => \'Test\',
    \'ip\' => \'24.99.127.23\',
  ),
)2021-5-04 20:48:50 - Pending Referral #346 created successfully.
2021-5-04 20:48:50 - Referral #346 created successfully.
2021-5-04 20:48:52 - Referral retrieved successfully during reject_referral()
2021-5-04 20:48:52 - Referral #346 set to Rejected successfully
2021-5-04 20:50:11 - WooCommerce Referral #346 updated successfully.
2021-5-04 20:50:14 - Referral retrieved successfully during complete_referral()
2021-5-04 20:50:14 - Referral #346 set to Unpaid successfully
2021-5-04 20:51:55 - Arguments being sent to DB:
array (
  \'amount\' => 1.8,
  \'reference\' => 1800,
  \'description\' => \'Happy Ninja\',
  \'campaign\' => \'\',
  \'affiliate_id\' => 9,
  \'visit_id\' => 93,
  \'order_total\' => \'18.00\',
  \'products\' => \'a:1:{i:0;a:4:{s:4:\"name\";s:11:\"Happy Ninja\";s:2:\"id\";i:37;s:5:\"price\";s:2:\"18\";s:15:\"referral_amount\";s:3:\"1.8\";}}\',
  \'custom\' => \'a:2:{s:12:\"affiliate_id\";i:9;s:18:\"is_coupon_referral\";b:0;}\',
  \'type\' => \'sale\',
  \'context\' => \'woocommerce\',
  \'customer\' => 
  array (
    \'user_id\' => 0,
    \'email\' => \'tjackstest38208@gmail.com\',
    \'first_name\' => \'Taylor\',
    \'last_name\' => \'Test\',
    \'ip\' => \'24.99.127.23\',
  ),
)2021-5-04 20:51:55 - Pending Referral #347 created successfully.
2021-5-04 20:51:55 - Referral #347 created successfully.
2021-5-04 20:51:58 - Referral retrieved successfully during reject_referral()
2021-5-04 20:51:58 - Referral #347 set to Rejected successfully
2021-5-04 20:52:21 - WooCommerce Referral #347 updated successfully.
2021-5-04 20:52:24 - Referral retrieved successfully during complete_referral()
2021-5-04 20:52:24 - Referral not marked as complete because of affwp_auto_complete_referral filter
2021-5-04 20:53:13 - Arguments being sent to DB:
array (
  \'amount\' => 1.8,
  \'reference\' => 1801,
  \'description\' => \'Happy Ninja\',
  \'campaign\' => \'\',
  \'affiliate_id\' => 9,
  \'visit_id\' => 93,
  \'order_total\' => \'18.00\',
  \'products\' => \'a:1:{i:0;a:4:{s:4:\"name\";s:11:\"Happy Ninja\";s:2:\"id\";i:37;s:5:\"price\";s:2:\"18\";s:15:\"referral_amount\";s:3:\"1.8\";}}\',
  \'custom\' => \'a:2:{s:12:\"affiliate_id\";i:9;s:18:\"is_coupon_referral\";b:0;}\',
  \'type\' => \'sale\',
  \'context\' => \'woocommerce\',
  \'customer\' => 
  array (
    \'user_id\' => 0,
    \'email\' => \'tjackstest38208@gmail.com\',
    \'first_name\' => \'Taylor\',
    \'last_name\' => \'Test\',
    \'ip\' => \'24.99.127.23\',
  ),
)2021-5-04 20:53:13 - Pending Referral #348 created successfully.
2021-5-04 20:53:13 - Referral #348 created successfully.
2021-5-04 20:53:15 - Referral retrieved successfully during reject_referral()
2021-5-04 20:53:15 - Referral #348 set to Rejected successfully
2021-5-04 20:53:28 - WooCommerce Referral #348 updated successfully.
2021-5-04 20:53:31 - Referral retrieved successfully during complete_referral()
2021-5-04 20:53:31 - Referral not marked as complete because of affwp_auto_complete_referral filter

**Comment by DrewAPicture** [comment]
Thanks for the detailed followup @tjackson1317, super helpful!

**Comment by tjackson1317** [comment]
Another check in by the same customer:

> Hope you're well.
> 
> Going through payments again this month and, well, you know the issue!
> 
> Any idea if this is being worked on at the moment for a fix?

**Comment by tjackson1317** [comment]
Reported by another customer:

> Hello, sometimes an order will time out in our system and it will be labeled as Cancelled or Failed, but the payment was successful. So in this situation we have to Change status to Processing/Completed. However, when we do this, the Referral still remains "Rejected". It does not automatically change back to "Pending".

https://secure.helpscout.net/conversation/1528199234/186036/

**Comment by tjackson1317** [comment]
@DrewAPicture Would it at all be possible to get a patch fix working for these customers? This issue creates quite a bit of manual work on the customers' part in the meantime, so thought it was worth it to ask at least.

(The first customer is using WC and the second is using both WC and MemberPress.)

**Comment by DrewAPicture** [comment]
Let me see what we can do. Realistically, this behavior is likely a bug in core AffiliateWP as triggered by the presence of the filter this add-on enables (this entire add-on is one line of code that hooks to a core filter).

**Comment by DrewAPicture** [comment]
I've added this to the 1.1.1 milestone and filed https://github.com/AffiliateWP/AffiliateWP/issues/3972 on the AffiliateWP core end to facilitate it.

I think we may be able to simply check for a 'rejected' status on the referral object in determining whether to allow the referral to be completed in this scenario.

**Comment by DrewAPicture** [comment]
PR: #20

**Comment by tjackson1317** [comment]
Was able to test the `issue/13` branch today, which does update the referral status automatically after the failed order is completed. However, I did find that it updates referrals to _Unpaid_, rather than to _Pending_.

**Comment by tjackson1317** [comment]
@DrewAPicture Haven't heard back from the customer yet, but FYI this worked beautifully in my own tests! ✨

**Comment by DrewAPicture** [comment]
Merged #20 against `release/1.1.1`
